---
- name: Install Nginx
  become: true
  ansible.builtin.yum:
    name: "{{ item }}"
  with_items:
    - epel-release
    - nginx
  notify: nginx systemd
- name: Create nginx config
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/conf.d/lighthouse.conf"
    mode: 0755
  notify: nginx reload