---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - my_clickhouse
- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - my_lighthouse
    - nginx
- name: Install Vector
  hosts: vector
  roles:
    - my_vector