---
dependency:
  name: galaxy
driver:
  name: podman
 platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    #privileged: true
    #uts: private
    #net: private
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - destroy